### ISSUE TITLE
::placeholder not vendor prefixed

### ISSUE THREAD

**Issue by jaydenseric** [thysultan/stylis.js#11]
`::placeholder` is not vendor prefixed: [caniuse](http://caniuse.com/#feat=css-placeholder).

**Comment by thysultan** [comment]
Thanks for opening this, have considered this before and forgot about it, do you know if this can be used as an element selector across browser implementations? i.e 

```scss
input.red:placeholder, 
input.error:placeholder {
    color:red;
}
```

**Comment by jaydenseric** [comment]
It should be double colon because it's a pseudo element.

You can not mixes vendor prefixes in one selector; the rules have to be duplicated.

In:

```css
input.red::placeholder, 
input.error::placeholder {
  color:red;
}
```

Out:

```css
input.red::-webkit-input-placeholder, 
input.error::-webkit-input-placeholder {
  color:red;
}
input.red:-ms-input-placeholder, 
input.error:-ms-input-placeholder {
  color:red;
}
input.red::placeholder, 
input.error::placeholder {
  color:red;
}
```

**Comment by thysultan** [comment]
added in v2.0.0

**Comment by evenchange4** [comment]
I create a PR #13 for nested use case:

In:

```css
input {
  &::placeholder {
    color:red;
  }
}
```

Out:

```css
input::-webkit-input-placeholder {
  color:red;
}
input::-moz-placeholderr {
  color:red;
}
input:-ms-input-placeholder {
  color:red;
}
input::placeholder {
  color:red;
}
```
