### ISSUE TITLE
custom-properties: don't overwrite, fall-back.

### ISSUE THREAD

**Issue by VinSpee** [thysultan/stylis.js#121]
Hi!

Currently, the custom-properties plugin will transform a custom-property statically. I think that possibly a more appropriate behavior would be to fall-back.

https://github.com/thysultan/stylis.js/blob/master/plugins/custom-properties/index.js#L36

for example:

## INPUT
```js
import stylis from "stylis";
import cp from "stylis-custom-properties";

stylis.use(cp);

return stylis(
  "#id",
  `
:global(:root) {--fs: 1em}
font-size: var(--fs, 10px);
`
);
```

## ACTUAL
```css
#id{
  font-size:1em;
}
```

## EXPECTED
```css
:root{
 --fs: 1em;
}
#id{
  font-size:1em;
  font-size:var(--fs, 10px);
}
```

this is [how postcss-custom-properties works](https://github.com/postcss/postcss-custom-properties#postcss-custom-properties-) and I think is what many would expect. Would you be open to a PR introducing this functionality?
