### ISSUE TITLE
Wrong output for nth-child() in combination with a class 

### ISSUE THREAD

**Issue by SimonSiefke** [thysultan/stylis.js#134]
I reported this issue to https://github.com/zeit/styled-jsx/issues/531 and was redirected to this project.

The problem is with nth-child() in combination with a class. For example:
```css
div:nth-child(1).green {
  background: green;
}
```

Current output: 
```css
div.jsx-2072553631:nth-child(1) .green.jsx-2072553631 {
  background: green;
}
```

Expected output: 
```css
div.jsx-2072553631:nth-child(1).green.jsx-2072553631 {
  background: green;
}
```

I should also mention that this happens with `cascade: false`
