### ISSUE TITLE
position: sticky autoprefix

### ISSUE THREAD

**Issue by vitordino** [thysultan/stylis.js#140]
just saw that although there are some lines about [`position: sticky`](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L1162-L1167), was unable to support `Safari v11` (Mac OS) and `Safari Mobile` (on iOS 11.4).

---

for work properly on these devices the line:
```css
div {
  position: sticky;
}
```

should be:
```css
div {
  position: sticky;
  position: -webkit-sticky;
}
```
