### ISSUE TITLE
& doesn't work after a block

### ISSUE THREAD

**Issue by wmertens** [thysultan/stylis.js#141]
See https://github.com/styled-components/babel-plugin-styled-components/issues/207 - I think

```scss
.foo{width:5em}&.bar{width:3em}
```

should be equivalent to
```scss
.foo{
  width:5em;
}
&.bar{
  width:3em;
}
```

but it seems that that's not the case
