### ISSUE TITLE
Stylis can't parse CSS Variables

### ISSUE THREAD

**Issue by tomhodgins** [thysultan/stylis.js#144]
Hello! I've just tried running known-valid CSS variable values through Stylis and it appears to have quite a few errors with how it's parsing CSS variable values.

Some examples of valid CSS variables that Stylis appears to have problems with include:

```css
--braces: { };
--at-keyword-unknown-block: @foobar {};
--at-keyword-known-block: @media {};
--cdo-at-top-level: <!--;
--cdc-at-top-level: -->;
--semicolon-not-top-level: (;);
--cdo-not-top-level: (<!--);
--cdc-not-top-level: (-->);
```

These values are taken directly from the Web Platform Tests file for what a legal CSS variable value should be: https://github.com/web-platform-tests/wpt/blob/master/css/css-variables/test_variable_legal_values.html#L64&L86

<img width="1065" alt="Screen Shot 2019-04-12 at 4 21 53 PM" src="https://user-images.githubusercontent.com/955601/56065022-ac827900-5d41-11e9-9e2a-1d5bb6882294.png">

It's not just these specific examples that are broken, but they seem to highlight that CSS variable values don't appear to be parsed according to the syntax described for them in the [CSS Variables spec](https://www.w3.org/TR/css-variables-1/#syntax) so there are likely many other examples that are valid that would also be broken.
