### ISSUE TITLE
Vendor prefix text-size-adjust

### ISSUE THREAD

**Issue by jaydenseric** [thysultan/stylis.js#15]
This:

```css
html {
  text-size-adjust: none;
}
```

should be vendor prefixed to:

```css
html {
  -webkit-text-size-adjust: none;
  text-size-adjust: none;
}
```

- https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust
- http://caniuse.com/#feat=text-size-adjust
