### ISSUE TITLE
Comments inside declaration block "increases" nesting of further selectors

### ISSUE THREAD

**Issue by Andarist** [thysultan/stylis.js#154]
**Repro**
```js
stylis('.test', `

font-size:2rem;
.one{color:black;/* foo */}
.two{color:black;/* bar */}
.three{color:black;/* baz */}

`)
```
**Actual**
```css
.test {
  font-size: 2rem;
}
.test .one {
  color: black;
}
.test .one .two {
  color: black;
}
.test .one .two .three {
  color: black;
}
```
**Expected**
```css
.test {
  font-size: 2rem;
}
.test .one {
  color: black;
}
.test .two {
  color: black;
}
.test .three {
  color: black;
}
```
