### ISSUE TITLE
@supports support

### ISSUE THREAD

**Issue by mxstbr** [thysultan/stylis.js#16]
`@supports` does not seem to work correctly. [Reproduction](https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN)

```CSS
// Input:
@supports (display: block) {
  background: mediumseagreen;
}

// Output:
@supports (display: block) {background-color: mediumseagreen;}
```

StackOverflow question that prompted this: https://stackoverflow.com/questions/43562789/using-supports-with-styled-components/43571955#43571955
