### ISSUE TITLE
Parsing error with version 2

### ISSUE THREAD

**Issue by didierfranc** [thysultan/stylis.js#17]
## What happened

I'm trying to use stylis with this input but it's not working with stylis 2.x 😕

```js
stylis(`.${hash}`, style)
```

### In
```css
  @media (max-width: 600px) {
    & { color: red }
  }

  &:hover {
    color: orange
  }
```

### Out - 1.2.8

```css
@media (max-width: 600px) {.OTIfQo {color: red}}.OTIfQo:hover {color: orange} 
```
### Out - 2.0.5 (fail) 
```css
.OTIfQo:hover {@media (max-width: 600px) {.OTIfQo {color: red}}color: orange} 
```
