### ISSUE TITLE
Invalid hidden characters inserted after commas

### ISSUE THREAD

**Issue by jaydenseric** [thysultan/stylis.js#18]
This is really weirding me out to debug, but I think this is an issue that has arisen in a recent version of Stylis.

With this input:

```css
html {
  font-family: 'Proxima Nova', 'Helvetica Neue', sans-serif;
}
```

Strange invisible characters get inserted just after the commas, that invalidates the whole rule in browsers. All my fonts are Times New Roman now :'(
