### ISSUE TITLE
Make tiny optimization to our CSS compiler to avoid extra trailing `;`

### ISSUE THREAD

**Issue by giuseppeg** [thysultan/stylis.js#20]
This is definitely a nice-to-have (not a big deal) but we could get rid of extra spaces and trailing `;` for smaller footprint.

**Comment by thysultan** [comment]
So

```css
h1 {
color: red;
}
```

would output

```css
h1{color:red}
```

At the moment it produces

```css
h1 {color: red;}
```

Would love to add this as an option in the rewrite[https://github.com/thysultan/stylis.js/tree/master/rewrite](https://github.com/thysultan/stylis.js/tree/master/rewrite)

Which supports styled-jsx cascade isolation out of the box as an option

```
stylis.set({
cascade: false
})
```
