### ISSUE TITLE
flex-direction autoprefixer for android 4.1 or 4.2

### ISSUE THREAD

**Issue by zD98** [thysultan/stylis.js#201]
Hi, I met a problem.

```css
{
flex-direction: column;
}
// converted in Android4.2 not working
{
-webkit-flex-direction: column;
}
// it will be working
{
-webkit-box-orient: vertical;
}
```
`-webkit-box-orient` is not in the standard, but it is useful for Android 4.2.

So could i have any suggestions to add `-webkit-box-orient` by using stylis.js ?
