### ISSUE TITLE
Syntax error in deep nesting

### ISSUE THREAD

**Issue by UpperCod** [thysultan/stylis.js#220]
Hi, I have detected in the received syntax as output the following example:

### Input : 

```css
.component{
	&.--state-a{	
		color:black;
		&.--state-a{	
			color:black;
		}
	}
}
```

### Output received: 

```css
[namespace] .component {
&.--state-a {
	color: black;
&.--state-a {
	color: black;
}
```
### Expected output:

```css
[namespace] .component.--state-a {
	color: black;
}

[namespace] .component.--state-a.--state-a {
	color: black;
}
```

I'm [reading the code](https://github.com/thysultan/stylis.js/blob/master/src/Parser.js#L119), to be able to contribute to stylis.
