### ISSUE TITLE
Add support for css media resolution vendor prefixing

### ISSUE THREAD

**Issue by lucianojss** [thysultan/stylis.js#224]
## Description

At the moment `stylis.js` does not support [media query resolution](https://caniuse.com/#feat=css-media-resolution) vendor prefixing.

## Example 

This input
```css
@media (min-resolution: 1dppx) {
    background-color: red;
  }
```
Should generate:
```css
@media (-webkit-min-device-pixel-ratio: 1), (min-resolution: 1dppx) {
    background-color: red;
}
```
What's the possibility to support this?
