### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by Tymek** [thysultan/stylis.js#234]
using Next.js I was directed here from https://github.com/vercel/styled-jsx/issues/504#issuecomment-428123209

This:
``` jsx
	<style global jsx>{`
		@font-face {
			font-family: 'Roboto';
			font-weight: 300;
			font-display: swap;
			src: local('Roboto'), url('/static/fonts/roboto-light.woff2') format('woff2');
		}

		@font-face {
			font-family: 'Roboto';
			font-weight: 700;
			font-display: swap;
			src: local('Roboto'), url('/static/fonts/roboto-bold.woff2') format('woff2');
		}

		@font-face {
			font-family: 'Roboto Mono';
			font-weight: 300;
			font-display: swap;
			src: local('Roboto Mono'), url('/static/fonts/roboto-mono-light.woff2') format('woff2');
		}

	`}
	</style>
```

is compiled to

``` css
@font-face{font-family:'Roboto';font-weight:300;font-display:swap;src:local('Roboto'),url('/static/fonts/roboto-light.woff2'):format('woff2');}@font-face{font-family:'Roboto';font-weight:700;font-display:swap;src:local('Roboto'),url('/static/fonts/roboto-bold.woff2'):format('woff2');}@font-face{font-family:'Roboto Mono';font-weight:300;font-display:swap;src:local('Roboto:Mono'),url('/static/fonts/roboto-mono-light.woff2') format('woff2');}
```

with errors like:
``` css
....woff2'):format('woff2');
```
``` css
src:local('Roboto:Mono'),url(...
```
