### ISSUE TITLE
[Plugin] how to add a rule based on a property declaration

### ISSUE THREAD

**Issue by hazem3500** [thysultan/stylis.js#237]
I am currently writing a plugin that converts CSS logical properties to directional properties inside a rule with a selector for the direction attribute
**Example**
from:
```css
padding-inline-start: 50px;
```
to
```css
padding-inline-start: 50px:
@supports not (padding-inline-start: 50px) {
  [dir=ltr] {
    padding-left: 50px;
  }
  [dir=rtl] {
    padding-right: 50px;
  }
}
```
My current implementation looks like this (simplified):
 ```jsx
import {compile} from 'stylis'

const PROPERTY_CONTEXT = 1;
function stylisPluginLogical(context, content) {
    if (context === PROPERTY_CONTEXT ) {
        const propertyAST = compile(content)[0];
        if (isALogicalProperty(propertyAST.props)) {
            return transforms[propertyAST.props](propertyAST.children);
        }
        return content;
    }
}

const transforms = {
  // ...
  "padding-inline-start": (value) => `
  padding-inline-start: ${value}:
  @supports not (padding-inline-start: ${value}) {
    [dir=ltr] {
      padding-left: ${value};
    }
    [dir=rtl] {
      padding-right: ${value};
    }
  }
  `
}
```
[Repo link](https://github.com/hazem3500/stylis-plugin-logical)

The problem is returning a nested rule with the property declaration doesn't work, so how can I inject this
```css
  @supports not (padding-inline-start: 50px) {
    [dir=ltr] {
      padding-left: 50px;
    }
    [dir=rtl] {
      padding-right: 50px
    }
  }
```
in another rule outside the rule that has the `padding-inline-start: 50px` in it?
