### ISSUE TITLE
@media as first child in rule does not compile

### ISSUE THREAD

**Issue by jwstegemann** [thysultan/stylis.js#239]
Hi,

the following string does not compile in stylis (version 4.0.2):

```css
.img-TYVie { 
	@media screen and (min-width: 48em) {
		width: 10rem;
	}
}
```

When I have some property before the `@media` (even some invalid), it works, so my workaround for now is:

```css
.img-TYVie { 
	dummy: 0;
	@media screen and (min-width: 48em) {
		width: 10rem;
	}
}
```
Since the css is generated at runtime it makes the code a lot more complex, if we would have to deal with empty outer rules in completely different way...
