### ISSUE TITLE
Namespace: :global selector and &

### ISSUE THREAD

**Issue by layershifter** [thysultan/stylis.js#252]
Hey folks! Thank you for the hard work there ❤️ 

---

I have following:

## Input

```css
.foo:global(.bar) { color: red }
```

## Output

```css
.bar{color:red;}
```

Is there any way to emit `.bar .foo{color:red;}`? I checked unit test cases and haven't found an answer there 😿
