### ISSUE TITLE
Namespace plugin: issue with preudo selectors

### ISSUE THREAD

**Issue by layershifter** [thysultan/stylis.js#253]
Hey folks!

It seems that there is something wrong in `namespace` plugin as output emitted with it looks completely incorrect 😿 
And ideas why it happens?

Stylis version: 4.0.6

### Input

```css
.foo:before {
  color: red;
}
.foo {
  :before {
    color: red;
  }
}
```

### Output with `namespace` plugin

```css
before.foo.foo {
  color: red;
}
:before.foo {
  color: red;
}
```

### Output without plugin

```css
.foo:before{color:red;}
.foo :before{color:red;}
```

**Comment by Andarist** [comment]
The output with the `namespace` plugin looks wrong. I would classify this as a bug - I won't have time to fix this myself as this plugin lies outside of my interests. I'm encouraging you to play with the codebase to provide a fixing PR.

Note that the actual output without the plugin is this:
```css
.foo:before{color:red;}
.foo :before{color:red;}"
```
