### ISSUE TITLE
Most of the rules with universal selector has stopped to work

### ISSUE THREAD

**Issue by soulchainer** [thysultan/stylis.js#26]
At some point, I think stylis has stopped supporting universal selectors :(.

When I do this (on the playground):

```css
.MyComponent > * {
  color: blue;
}
```

it outputs:

```css
.MyComponent > {
  color: blue;
}
```

And well, in every position I try to use a universal selector. It's this intended?

I just updated `styled-jsx` from `0.5.7` to `1.0.0`. Previously, this same rules were working and, with this update, all got broken >_<.
