### ISSUE TITLE
How to replace a node?

### ISSUE THREAD

**Issue by joelmoss** [thysultan/stylis.js#261]
I have this CSS:

```css
body {
  @mixin container;
  color: red;
}
```

And want to replace the `@mixin container;` line with additional CSS. For example:

```css
font-size: 12px;
a {
  color: pink;
}
```

My output should be 

```css
body {
  font-size: 12px;
  color: red;
  a {
    color: pink;
  }
}
```

So in my middleware, I can check for the `@mixin` type:

```js
if (element.type === '@mixin') {
  // ??
}
```

but how to replace the node with the above CSS?

thx
