### ISSUE TITLE
Unexpected scoping with pseudo selectors

### ISSUE THREAD

**Issue by nstepien** [thysultan/stylis.js#267]
See https://github.com/callstack/linaria/issues/782

---

input:
```js
css`
  .a {
    .b & {
      color: blue;
    }
  }
`;

css`
  .c {
    :hover & {
      color: red;
    }
  }
`;
```

output:
```css
.b .s1waqsbb .a {
  color: #00f;
}

.syp60te .c:hover .syp60te .c {
  color: red;
}
```

I expect the `&` to take precedence, so it should be
```diff
-.syp60te .c:hover .syp60te .c {
+:hover .syp60te .c {
```

---

input:
```js
const parentA = css``;
const parentB = css``;
const parentC = css``;
const activeLink = css``;

const link = css`
  all: unset;

  :is(:hover, :focus, .${activeLink}) {
    color: red;

    :is(.${parentA}, .${parentB}) & {
      content: '';
    }

    .${parentC} & {
      color: blue;
    }
  }
`;
```
output:
```css
.lc7u01 {
  all: unset;
}

.lc7u01:is(:hover, :focus, .a1lslk66) {
  color: red;
}

.lc7u01:is(:hover, :focus, .a1lslk66):is(.p1waqsbb, .pyp60te) .lc7u01:is(:hover, :focus, .a1lslk66) {
  content: \"\";
}

.p4g1w4s .lc7u01:is(:hover, :focus, .a1lslk66) {
  color: #00f;
}
```

I expect this instead
```diff
-.lc7u01:is(:hover, :focus, .a1lslk66):is(.p1waqsbb, .pyp60te) .lc7u01:is(:hover, :focus, .a1lslk66) {
+:is(.p1waqsbb, .pyp60te) .lc7u01:is(:hover, :focus, .a1lslk66) {
```
I know I can do `.${parentA} &, .${parentB} & {}`, but that defeats the optimizations `:is()` offers.

Using `:global()` does not help: https://github.com/callstack/linaria/issues/782#issuecomment-865893718

---

Is that expected?
