### ISSUE TITLE
Referencing & from within :not()

### ISSUE THREAD

**Issue by stonebk** [thysultan/stylis.js#272]
A bit of an odd case, but do you think this is behaving correctly?

```css
.foo {
    .bar:not(&) {
        color: red;
    }
}
```

I would have expected this to produce:

```css
.bar:not(.foo) {
    color: red;
}
```

Instead it seems to ignore the ampersand inside `:not()`:

![Screen Shot 2021-09-09 at 2 38 46 PM](https://user-images.githubusercontent.com/1432010/132766222-81cd3642-a8e4-4468-a534-94a7ed806978.png)

**Comment by Andarist** [comment]
https://www.sassmeister.com/ thinks that this is not right. The expected output there is:
```css
.bar:not(.foo) {
  color: red;
}
```

**Comment by stonebk** [comment]
Some mixed results playing with other selectors:

```css
.foo {
    :not(&) {
        color: red;
    }
    :matches(&) {
        color: red;
    }
    :is(&) {
        color: red;
    }
    :any(&) {
        color: red;
    }
    :where(&) {
        color: red;
    }
    :has(&) {
        color: red;
    }
}
```

```css
:not(.foo) {
  color: red;
}
:matches(.foo) {
  color: red;
}
.foo :is(&) {
  color: red;
}
:any(.foo) {
  color: red;
}
.foo :where(&) {
  color: red;
}
:has(.foo) {
  color: red;
}
```
