### ISSUE TITLE
Prefix inside `@supports` declaration

### ISSUE THREAD

**Issue by jacobbuck** [thysultan/stylis.js#34]
Input:

```css
/* @scope .foo */

input {
	@supports (appearance: none) {
		appearance: none;
	}
}
```

Expected result:

```css
@supports ((-webkit-appearance: none) or (-moz-appearance: none) or (appearance: none)) {
	.foo input {
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
	}
}
```

Actual result:

```css
@supports (appearance: none) {
	.foo input {
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
	}
}
```

**Comment by thysultan** [comment]
Interesting, i'm trying to understand why it would be used like that though since `@supports` suggests find granular control of feat support sniffing. In such a case what would be the difference between the following...

```css
input {
	@supports ((-webkit-appearance: none) or (-moz-appearance: none) or (appearance: none)) {
	      -webkit-appearance: none;
              -moz-appearance: none;
	      appearance: none;
	}
}
```

and

```css
input {
        -webkit-appearance: none;
        -moz-appearance: none;
	appearance: none;
}
```
