### ISSUE TITLE
Print styles

### ISSUE THREAD

**Issue by mxstbr** [thysultan/stylis.js#44]
## Input

```javascript
injectGlobal`
  @page {
    size: A4 landscape;
  }
  @page :left {
    margin-left: 3cm;
  }
  @media (max-width: 700px) {
    html {
      background: palevioletred;
    }
  }
`
```

## Expected Behavior
style tag in server side rendered head with
```css
@page{size: A4 landscape;}
@page :left{margin-left: 3cm;}
@media (max-width: 700px){html{background: palevioletred;}}
```

## Actual Behavior
style tag in server side rendered head with
```css
@page{{size: A4 landscape;}}
@page :left{{margin-left: 3cm;}}
@media (max-width: 700px){html{background: palevioletred;}}
```

----

Copied from https://github.com/styled-components/styled-components/issues/957
