### ISSUE TITLE
can't parse attribute selectors after another selector

### ISSUE THREAD

**Issue by eranshabi** [thysultan/stylis.js#48]
given this css:
```css
.foo { color: white; }[role=button]{cursor:pointer}
```
stylis will stop parsing at `[role=button]` and will return only `.foo { color: white; }`
