### ISSUE TITLE
grid-template-areas after first string is not being passed to the browser

### ISSUE THREAD

**Issue by johhansantana** [thysultan/stylis.js#49]
ide:
<img width="390" alt="screen shot 2017-07-23 at 2 58 01 pm" src="https://user-images.githubusercontent.com/9933887/28502036-b4d104b0-6fb7-11e7-8774-47c0c07b94d5.png">

browser:
<img width="309" alt="screen shot 2017-07-23 at 2 57 51 pm" src="https://user-images.githubusercontent.com/9933887/28502037-b4eaba22-6fb7-11e7-909e-4e157b33aa81.png">

as you can see, the second line for the `grid-template-areas` is not being passed to the browser.

Is there a way to fix this?

**edit**
Making it inline seems to work but it should work both ways

```css
.mainContainer {
  width: 80vw;
  margin: auto;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: auto;
  grid-template-areas:
    "header header header" ". main .";
}
```
