### ISSUE TITLE
Vendor prefix mask-image

### ISSUE THREAD

**Issue by jaydenseric** [thysultan/stylis.js#55]
This:

```css
div {
  mask-image: linear-gradient(transparent, black); 
}
```

Should vendor prefix to this:

```css
div {
  -webkit-mask-image: -webkit-linear-gradient(transparent, black);
  mask-image: linear-gradient(transparent, black);
}
```

See http://caniuse.com/#feat=css-masks
