### ISSUE TITLE
wrong output when left value is 0 without units

### ISSUE THREAD

**Issue by felixmosh** [thysultan/stylis.js#57]
For example, 

```css
.foo{padding:30px 0}
```
will produce output of
```css
.foo{padding:30px0}
```

Same result with `margin`
