### ISSUE TITLE
Remove rules with empty attributes

### ISSUE THREAD

**Issue by wmertens** [thysultan/stylis.js#58]
See https://github.com/styled-components/styled-components/issues/1110

It would be great if stylis removed all these empty examples:

```
.emptyAttr { color: ; } // should be removed
.spuriousSemi { color: black; ; ; ; ; } // should only keep color: black
.emptySelector { } // should be removed
```

**Comment by thysultan** [comment]
The last two are removed.

```css
.spuriousSemi { color: black; ; ; ; ; } // should only keep color: black
.emptySelector { } // should be removed
```
