### ISSUE TITLE
Prepending & to nested pseudo selectors

### ISSUE THREAD

**Issue by seanevd** [thysultan/stylis.js#64]
I'm not sure if this is a bug, but I thought I'd ask since I saw this in some code I was reviewing the other day. This is styled-components. It compiles out correctly, but I didn't see it in the docs, anywhere.
```
const example = styled.div`
  color: green
  ::after {
    background: yellow;
  }
`;
```
The thing that is strange is that ::after pseudo selector does not have an & prepending it to the selector. Is this expected behavior, I don't think it works in scss (not sure if that's something you compare against). Just FYI.

**Comment by thysultan** [comment]
Your right, it won't work in [scss](https://www.sassmeister.com/gist/a00d32b8ac6c0cdec706f595d63b0b63), however it is an intentional behavior here. Does the current behavior break something in your app?

**Comment by seanevd** [comment]
No, it doesn't break anything, it's working fine. I'm just a long time Sass user and thought it would break or not render correctly. Why is it intentional? Is there somewhere I could read more about this?

**Comment by thysultan** [comment]
>Why is it intentional?

Mainly DX, given that orphaned `:active{}` pseudo selectors are invalid css – stylis would use the surrounding namespace similar to how it might fix other invalid css patterns, i.e missing colons/semicolons etc.

**Comment by elektronik2k5** [comment]
I too thought it's a bug. Should be documented, as it isn't what preprocessor users are used to. @thysultan would you like me to make a PR?

**Comment by thysultan** [comment]
@elektronik2k5 Yes, that would be great.

**Comment by bensaufley** [comment]
@thysultan I'm trying to find where this is explicitly stated:

> given that orphaned `:active{}` pseudo selectors are invalid css

Can you point me somewhere? I'm looking at the [Selectors Level 3 spec](https://drafts.csswg.org/selectors-3/#pseudo-classes) and I don't see anything but I might be missing it. It _seems_ like this says otherwise (emphasis mine):

> Pseudo-classes are allowed anywhere in sequences of simple selectors, after the leading type selector or universal selector **(possibly omitted).**

It's not a rule I was aware of, and I feel like standalone pseudo-classes have worked for me in the past. For what it's worth, [this codepen with a bunch of orphaned pseudo-classes and pseudo-elements](https://codepen.io/bensaufley/pen/GXpEaq) works for me on MacOS Chrome 68, Firefox 61, and Safari 11.1.2; as well as Edge 17 and IE11 on Windows 10.

In the meantime I'm able to do things like `& :checked` to force the space as needed, so it's certainly not the end of the world, but I think that the fact that nesting with and without `&` isn't consistent feels like a bug (also, yes, coming from SCSS it's hard to adjust/predict):

```scss
div {
  .class {
    color: blue;
  }

  &.class {
    color: green;
  }

  :hover {
    color: red;
  }

  &:hover {
    color: orange;
  }
}

// outputs:
div .class { color: blue; } // all elements with classname of "class" inside divs
div.class { color: green } // all divs with classname of "class"
div:hover { color: red; } // all divs in hover state <- would expect "all hover elements inside divs"
div:hover { color: orange; } // all divs in hover state
```
