### ISSUE TITLE
[bug][plugin] nested custom property overrides property permanently 

### ISSUE THREAD

**Issue by Andarist** [thysultan/stylis.js#84]
**Input**
```js
stylis('.test', `
  --main-color: red;
  & {
    color: var(--main-color);
  };

  div {
    --main-color: green;
    
    span {
      background-color: var(--main-color);
    };
  };

  #should-be-red {
    color: var(--main-color);
  };
`)
```
**actual**
```css
.test{color:red;}.test div span{background-color:green;}.test #should-be-red{color:green;}
```
**expected**
```css
.test{color:red;}.test div span{background-color:green;}.test #should-be-red{color:red;}
```
