### ISSUE TITLE
Support stretch css keyword.

### ISSUE THREAD

**Issue by cameron-martin** [thysultan/stylis.js#94]
`stretch` is a valid value for the `width` and `height` properties, and is a part of the [intrinsic and extrinsic sizing module](https://www.w3.org/TR/css-sizing-3/#width-height-keywords).

It is already available in browsers using `-webkit-fill-available` and `-moz-available`. Autoprefixer transforms this:

```css
.example {
    width: stretch;
}
```

to

```css
.example {
    width: -webkit-fill-available;
    width: -moz-available;
    width: stretch;
}
```

It would be nice if stylis did this too.

**Comment by thysultan** [comment]
Thanks, i'll add this in the next patch.

**Comment by thysultan** [comment]
What is the difference between `stretch ` and `fill-available`(unprefixed varient)?

**Comment by thysultan** [comment]
i.e for

```css
.foo {
width:stretch;
}

.bar {
width:fill-available;
}
```

autoprefixer would convert this to

```css
.foo {
width:-webkit-fill-available;
width:-moz-available;
width:stretch;
}

.bar {
width:-webkit-fill-available;
width:-moz-available;
width:fill-available;
}
```
