### ISSUE TITLE
Wrong transformation on multiple selectors + :global() + line break 

### ISSUE THREAD

**Issue by nkzawa** [thysultan/stylis.js#97]
See https://github.com/zeit/styled-jsx/issues/411

on https://stylis.js.org:

```css
.foo :global(path),
.bar
   :global(path) {
   stroke: #067df7;
 }
```

is transpiled to:

```css
.scope {
	.foo : global(path),.bar;
}

path {
	stroke: #067df7;
}
```
